### ISSUE TITLE
about add Park into config["map"]

### ISSUE THREAD

**Issue by ZhenZhuHuang** [metadriverse/metadrive#202]
When I supposed to add "P"  in the config["map"]:
`config["map"] = "SPS"`
However, the following error occurred：

 AssertionError: Lane number of previous block must be 1 in each direction
Why about that ，and how can I add a Park part?

**Comment by QuanyiLi** [comment]
Hi,

The error is thrown because the first Straight block has 3 lanes, while the ParkingLot block can only connect to blocks with a single lane. 

So please use the following config to get an "SPS" style map:
``` 
from metadrive.component.map.base_map import BaseMap
from metadrive.component.map.pg_map import MapGenerateMethod

env_config=dict(
    map_config= {
                BaseMap.GENERATE_TYPE: MapGenerateMethod.BIG_BLOCK_SEQUENCE,
                BaseMap.GENERATE_CONFIG: "SPS",  # it can be a file path / block num / block ID sequence
                BaseMap.LANE_WIDTH: 3.5,
                BaseMap.LANE_NUM: 1,
                "exit_length": 50,
            }, 
    other_config= ...)
```
If you want to increase or decrease the number of lanes, you can try using [bottleneck blocks](https://github.com/metadriverse/metadrive/blob/main/metadrive/component/pgblock/bottleneck.py). These blocks can change the number of lanes in other blocks except ParkingLot.

Quanyi
