### ISSUE TITLE
blank grey screen

### ISSUE THREAD

**Issue by MoreTore** [metadriverse/metadrive#289]
installed as a submodule in exsisting repo. 
ran pip install -e .

when i run the examples I get a blank grey window.

works if i install with pip install metadrive-simulator directly

**Comment by QuanyiLi** [comment]
Hi,

The versioin installed via pip stays behind the newest ```main``` branch. Thus, it might be some new patches/updates in the latest MetaDrive which cause your problem. 

Could you help me do a simple validation? It is really easy. Just switch to the ```0.2.6``` release branch in your local repo via ```git checkout git checkout releases/0.2.6.0``` and see if the problem is solved or not. If so, my guess is correct. Otherwise, the issue will be complex.

Also, could you provide more information about your platform, *i.e.* OS/CPU/GPU and so on? Maybe I can try reproduce it. Thanks!

Quanyi

**Comment by MoreTore** [comment]
Yea I tried releases/0.2.6.0 and it's the same issue. I am going to assume it's my WSL2 setup since it usually has weird issues like this.

**Comment by QuanyiLi** [comment]
WSL2? That is interesting. Do WSL2 support opening window from any application now? I remember that it was only optimized to visualize rare applications like Chrome. Or do you use an XServer to do visualization? I am done with dual-boot, if the visualization is supported, I will delete the Ubuntu on my laptop right now, lol

**Comment by MoreTore** [comment]
Oh yea I got everything I use running in wsl2 now. There are just different bugs to work out than when running natively. Here is a video of what I'm working on. https://www.youtube.com/watch?v=P-ti8c1esiY&ab_channel=MoreTorque

**Comment by pengzhenghao** [comment]
The video is so cool!
