### ISSUE TITLE
Document broken: https://metadrive-simulator.readthedocs.io/en/latest/sensors.html

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#643]
https://metadrive-simulator.readthedocs.io/en/latest/sensors.html

![Screenshot from 2024-02-13 14-22-47](https://github.com/metadriverse/metadrive/assets/22206995/d34a9cb0-107b-4c10-ba45-4169508f3581)

**Comment by QuanyiLi** [comment]
I left this here on purpose. I wanna know if the readthedoc sever can render 3D scenes and this bug occurs. It is likely we can fix it. I will do this when I am free, so we can generate 3D content in the doc compile time.

**Comment by pengzhenghao** [comment]
It can be solved by #644

**Comment by pengzhenghao** [comment]
How I make this notebook compiled again? The #644 should already fix this?

**Comment by QuanyiLi** [comment]
Firstly, you can build the doc locally, to see if this cell runs and outputs the expected results. If the cell does not run, you have to enable the running in compiling time for that `.ipynb` according to the readme in the documentation. If the cell runs and produces correct results, that means it is still not fixed by #644. As when you merge #644, the doc should be compiled again...
